### ISSUE TITLE
Overriding core field settings in schema_fields.yml

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#1043]
If we try to change the settings of a core field via the `schema_fields.yml` file, a duplicate field is created. For example, we could choose to give description a display transformation in the collection schema:

```
- schema: 'Collection'
    fields:
      acknowledgments:
        order_index: 2
      narrative:
        order_index: 1
      access_rights:
        order_index: 3
      description:
        display_transformation: 'some_transformation'
```
However, this would result in two description fields in the collection schema instead of the one overriding the other.
